version: "3"

services:
  api:
    build: ./
    image: news_hack
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
  cache:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  