version: "3"

services:
  api:
    build: ./
    image: news_hack
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  redis_cache:
      image: redis:latest

      ports:
          - 6379:6379
      volumes:
          - ./config/redis.conf:/redis.conf
      command: [ "redis-server", "/redis.conf" ]
  