version: "3"

services:
  api:
    build: ./
    image: news_hack
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: "always"
    ports:
      - 8000:8000

  redis_cache:
      image: redis:latest
      restart: "always"
      ports:
          - 6579:6579
      volumes:
          - ./config/redis.conf:/redis.conf
      command: [ "redis-server", "/redis.conf" ]